MVC/Zadatak/Controllers/MojController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml;
using System.Xml.Serialization;
using Zadatak.Models;
using Zadatak.Models.Database;

namespace Zadatak.Controllers
{
    public class MojController : Controller
    {
        IRepository<PutniNalog> putniNalogRepository = new PutniNalogRepository();
        IRepository<Vozilo> voziloRepository = new VoziloRepository();
        IRepository<Vozac> vozacRepository = new VozacRepository();
        IRepository<Drzava> drzavaRepository = new DrzavaRepository();
        IRepository<Grad> gradRepository = new GradRepository();
        RelacijaRepository relacijaRepository = new RelacijaRepository();
        IRepository<KategorijaTroska> kategorijaTrosakRepository = new KategorijaTrosakRepository();
        IRepository<Servis> servisRepository = new ServisRepository();
        IRepository<KategorijaServis> kategorijaServisRepository = new KategorijaServisRepository();
        private PPPKEntities5 db = new PPPKEntities5();
        // GET: Moj
        public ActionResult Index()
        {
            return View();
        }

        public void PovratiBazu()
        {

        }

        [HttpGet]
        public ActionResult Filter(string searchQuery, string filterProp)
        {
            
            List<PutniNalog> filtered = putniNalogRepository.List().ToList();
            if (searchQuery == null)
                filterProp = null;
            foreach (var item in filtered)
            {
                
            }
            foreach (PutniNalog nalog in putniNalogRepository.List().ToList())
            {
                switch(filterProp)
                {
                    case "Ime":
                    Vozac vozac = vozacRepository.GetById(nalog.VozacID);
                    if (!vozac.FirstName.Contains(searchQuery) && !vozac.LastName.Contains(searchQuery))
                    {
                        filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                    }
                    break;
                    case "Vozilo":
                        Vozilo vozilo = voziloRepository.GetById(nalog.VoziloID);
                        if (!vozilo.Marka.Contains(searchQuery) && !vozilo.Tip.Contains(searchQuery))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                    case "Datum odlaska":

                        string[] dateParts = searchQuery.Split('/');
                        DateTime date = new DateTime(
                            int.Parse(dateParts[2]),
                            int.Parse(dateParts[1]),
                            int.Parse(dateParts[0]));
                        if(!(nalog.DatumOdlaska == date))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                    case "Datum dolaska":
                        dateParts = searchQuery.Split('/');
                        date = new DateTime(
                            int.Parse(dateParts[2]),
                            int.Parse(dateParts[1]),
                            int.Parse(dateParts[0]));
                        if (!(nalog.DatumDolaska == date))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                    case "Broj sati":
                        int brojSati;
                        bool success = int.TryParse(searchQuery, out brojSati);
                        if(success && !(brojSati == nalog.BrojSati))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                    case "Broj dnevnica":
                        int brojDnevnica;
                        success = int.TryParse(searchQuery, out brojDnevnica);
                        if (success && !(brojDnevnica == nalog.BrojDnevnica))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                    case "Iznos dnevnice":
                        int iznosDnevnice;
                        success = int.TryParse(searchQuery, out iznosDnevnice);
                        if (success && !(iznosDnevnice == nalog.IznosDnevnice))
                        {
                            filtered.RemoveAll(pn => pn.IDPutniNalog == nalog.IDPutniNalog);
                        }
                        break;
                }

            }
            List<PutniNalogViewModel> model = new List<PutniNalogViewModel>();
            foreach (PutniNalog item in filtered)
            {
                PutniNalogViewModel putniNalogVM = new PutniNalogViewModel
                {
                    Vozac = vozacRepository.GetById(item.VozacID),
                    Vozilo = voziloRepository.GetById(item.VoziloID),
                    BrojDnevnica = item.BrojDnevnica,
                    BrojSati = item.BrojSati,
                    IDPutniNalog = item.IDPutniNalog.Value,
                    IznosDnevnice = item.IznosDnevnice,
                    Opis = item.Opis,
                    DatumDolaska = item.DatumDolaska,
                    DatumOdlaska = item.DatumOdlaska
                };
                putniNalogVM.NamjestiStanje();
                model.Add(putniNalogVM);
            }
            return PartialView("_PutniNalogTablica", model);

        }

        public FileResult ExportVozilo(int idVozilo)
        {
            // Vozilo vozilo = voziloRepository.GetById(idVozilo);
            Vozila vozilo = db.GetVozilo(idVozilo).FirstOrDefault();
            IEnumerable<Servi> servisi = db.GetServisi().Where(servis => servis.VoziloID == idVozilo).ToList();
            if(vozilo != null)
            {
                StringWriter stringWriter = new StringWriter();
                using (HtmlTextWriter writer = new HtmlTextWriter(stringWriter))
                {

                    writer.RenderBeginTag(HtmlTextWriterTag.H1);
                    writer.Write("IZVJEŠTAJ VOZILA " + idVozilo);
                    writer.RenderEndTag();

                    writer.AddAttribute(HtmlTextWriterAttribute.Id, idVozilo.ToString());
                    writer.RenderBeginTag(HtmlTextWriterTag.Div); 


                    writer.RenderBeginTag(HtmlTextWriterTag.P);
                    writer.Write("Vozilo: " + vozilo.Marka);
                    writer.RenderEndTag();

                    writer.RenderBeginTag(HtmlTextWriterTag.P);
                    writer.Write("Tip: " + vozilo.Tip);
                    writer.RenderEndTag();

                    writer.RenderBeginTag(HtmlTextWriterTag.P);
                    writer.Write("Kilometri: " + vozilo.StanjeKilometra);
                    writer.RenderEndTag();

                    writer.RenderBeginTag(HtmlTextWriterTag.P);
                    writer.Write("Godina proizvodnje: " + vozilo.GodinaProizvodnje);
                    writer.RenderEndTag();

                    writer.RenderBeginTag(HtmlTextWriterTag.P);
                    writer.Write("Servis odraden: " + servisi.Count() + " puta");
                    writer.RenderEndTag();

                    if(servisi.Count() > 0)
                    {
                        writer.RenderBeginTag(HtmlTextWriterTag.Table);
                        writer.RenderBeginTag(HtmlTextWriterTag.Thead);
                        writer.RenderBeginTag(HtmlTextWriterTag.Tr);

                        writer.RenderBeginTag(HtmlTextWriterTag.Th);
                        writer.Write("Datum");
                        writer.RenderEndTag();

                        writer.RenderBeginTag(HtmlTextWriterTag.Th);
                        writer.Write("Kategorija");
                        writer.RenderEndTag();

                        writer.RenderBeginTag(HtmlTextWriterTag.Th);
                        writer.Write("Cijena");
                        writer.RenderEndTag();

                        writer.RenderEndTag();

                        writer.RenderBeginTag(HtmlTextWriterTag.Tbody);

                        foreach (var servis in servisi.ToList())
                        {
                            writer.RenderBeginTag(HtmlTextWriterTag.Tr);


                            writer.RenderBeginTag(HtmlTextWriterTag.Td);
                            writer.Write(servis.Datum.Value.ToShortDateString());
                            writer.RenderEndTag();

                            writer.RenderBeginTag(HtmlTextWriterTag.Td);
                            writer.Write(servis.KategorijaServi.Naziv);
                            writer.RenderEndTag();

                            writer.RenderBeginTag(HtmlTextWriterTag.Td);
                            writer.Write(servis.Cijena + " kn");
                            writer.RenderEndTag();

                            writer.RenderEndTag();

                        }

                        writer.RenderEndTag();
                        writer.RenderEndTag();
                        writer.RenderEndTag();
                    }


                // TABLICA KRAJ

                    writer.RenderEndTag(); // End #1

                }
                StringBuilder path = new StringBuilder();

                path.Append(Server.MapPath("/")).Append("Reports\\").Append("REP-").Append(idVozilo).Append(".html");
                using (StreamWriter file = new StreamWriter(path.ToString()))
                {
                    file.WriteLine(stringWriter.ToString()); // "sb" is the StringBuilder

                }

MVC/Zadatak/Controllers/RelacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Zadatak.Models;
using Zadatak.Models.Database;

namespace Zadatak.Controllers
{
    public class RelacijaController : Controller
    {
        IRepository<PutniNalog> putniNalogRepository = new PutniNalogRepository();
        IRepository<Vozac> vozacRepository = new VozacRepository();
        IRepository<Vozilo> voziloRepository = new VoziloRepository();
        RelacijaRepository relacijaRepository = new RelacijaRepository();
        IRepository<Drzava> drzavaRepository = new DrzavaRepository();
        IRepository<Grad> gradRepository = new GradRepository();
        // GET: Relacija
        public ActionResult Index()
        {
            List<Relacija> relacije = relacijaRepository.List().ToList();
            List<RelacijaViewModel> model = new List<RelacijaViewModel>();
            foreach (Relacija r in relacije)
            {
                RelacijaViewModel rvm = new RelacijaViewModel
                {
                    IDRelacija = r.IDRelacija.Value,
                    GradPolazak = gradRepository.GetById(r.GradPolazakID),
                    GradDolazak = gradRepository.GetById(r.GradDolazakID),
                    Kilometraza = r.Kilometraza,
                    PutniNalog = putniNalogRepository.GetById(r.PutniNalogID),
                    PrijevozIznos = r.PrijevozIznos
                };

                rvm.PutniNalog.Vozac = vozacRepository.GetById(rvm.PutniNalog.VozacID);
                model.Add(rvm);

            }
            return View(model);
        }

        // GET: Relacija/Details/5
        public ActionResult Details(int id)
        {
            //Relacija r = SqlHandler.GetRelacije().ToList().Find(rl => rl.IDRelacija == id);
            Relacija r = relacijaRepository.GetById(id);
            RelacijaViewModel rvm = new RelacijaViewModel
            {
                IDRelacija = r.IDRelacija.Value,
                GradPolazak = gradRepository.GetById(r.GradPolazakID),
                GradDolazak = gradRepository.GetById(r.GradDolazakID),
                Kilometraza = r.Kilometraza,
                PutniNalog = putniNalogRepository.GetById(r.PutniNalogID),
                PrijevozIznos = r.PrijevozIznos
            };
            return View(rvm);
        }

        // GET: Relacija/Create
        public ActionResult Create()
        {
            var model = new RelacijaViewModel
            {
                ListaDrzava = drzavaRepository.List(),
                ListaGradova = gradRepository.List(),
                ListaPutnihNaloga = putniNalogRepository.List(),
                ListaVozaca = vozacRepository.List(),
                ListaVozila = voziloRepository.List(),
            };
            foreach (var nalog in model.ListaPutnihNaloga)
            {
            nalog.Vozac = vozacRepository.GetById(nalog.VozacID);

            }
            return View(model);
        }

        // POST: Relacija/Create
        [HttpPost]
        public ActionResult Create(RelacijaViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Relacija relacija = new Relacija
                    {
                        GradPolazakID = model.GradPolazakID,
                        GradDolazakID = model.GradDolazakID,
                        PutniNalogID = model.PutniNalogID,
                        Kilometraza = model.Kilometraza,
                        PrijevozIznos = model.PrijevozIznos,
                    };
                    relacijaRepository.Add(relacija);
                }
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Relacija/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Relacija relacija= relacijaRepository.GetById(id);
            if (relacija == null)
            {
                return HttpNotFound();
            }
            var model = new RelacijaViewModel
            {
                ListaGradova = gradRepository.List(),
                ListaVozaca = vozacRepository.List(),
                ListaDrzava = drzavaRepository.List(),
                ListaPutnihNaloga = putniNalogRepository.List(),
                GradPolazakID = relacija.GradPolazakID,
                GradDolazakID = relacija.GradDolazakID,
                PutniNalogID = relacija.PutniNalogID,
                Kilometraza = relacija.Kilometraza,
                PrijevozIznos = relacija.PrijevozIznos,
                IDRelacija = relacija.IDRelacija.Value

            };
            foreach (var nalog in model.ListaPutnihNaloga)
            {
                nalog.Vozac = vozacRepository.GetById(nalog.VozacID);

            }
            //ViewBag.VozacID = new SelectList(Models.SqlHandler.GetVozaci(), "IDVozac", "FirstName", putniNalog.VozacID);
            // ViewBag.VoziloID = new SelectList(Models.SqlHandler.GetVozila(), "IDVozilo", "FirstName", putniNalog.VozacID);
            return View(model);
        }

        // POST: Relacija/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RelacijaViewModel model)
        {
            if (ModelState.IsValid)
            {
                Relacija relacija = new Relacija
                {
                    IDRelacija = model.IDRelacija,
                    GradPolazakID = model.GradPolazakID,
                    GradDolazakID = model.GradDolazakID,
                    PutniNalogID = model.PutniNalogID,
                    Kilometraza = model.Kilometraza,
                    PrijevozIznos = model.PrijevozIznos
                };
                relacijaRepository.Update(relacija);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Relacija/Delete/5
        public ActionResult Delete(int id)
        {
            Relacija r = relacijaRepository.GetById(id);
            RelacijaViewModel rvm = new RelacijaViewModel
            {
                IDRelacija = r.IDRelacija.Value,
                GradPolazak = gradRepository.GetById(r.GradPolazakID),
                GradDolazak = gradRepository.GetById(r.GradDolazakID),
                Kilometraza = r.Kilometraza,
                PutniNalog = putniNalogRepository.GetById(r.PutniNalogID),
                PrijevozIznos = r.PrijevozIznos
            };
            return View(rvm);
        }

        // POST: Relacija/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                relacijaRepository.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/Zadatak/Views/Relacija/Create.cshtml
@model Zadatak.Models.RelacijaViewModel

@{
    ViewBag.Title = "Dodaj novu relaciju";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Dodavanje relacije</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.GradPolazakID, "Grad polazak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GradPolazakID", new SelectList(Model.ListaGradova, "IDGrad", "Naziv", "---odaberi---"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GradDolazakID, "Grad dolazak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GradDolazakID", new SelectList(Model.ListaGradova, "IDGrad", "Naziv", "---odaberi---"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PutniNalogID, "Putni nalog", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PutniNalogID", new SelectList(Model.ListaPutnihNaloga, "IDPutniNalog", "PrikazNaloga", "---odaberi---"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Kilometraza, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Kilometraza, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kilometraza, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrijevozIznos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrijevozIznos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrijevozIznos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dodaj" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/Zadatak/Views/Relacija/Delete.cshtml
@model Zadatak.Models.RelacijaViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RelacijaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDRelacija)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDRelacija)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradPolazakID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradPolazakID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradDolazakID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradDolazakID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PutniNalogID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PutniNalogID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kilometraza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kilometraza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrijevozIznos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrijevozIznos)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/Zadatak/Views/Relacija/Details.cshtml
@model Zadatak.Models.RelacijaViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalji</h2>

<div>
    <h4>Relacija</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDRelacija)
        </dt>

        <dd id="idRel">
            @Html.DisplayFor(model => model.IDRelacija)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradPolazakID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradPolazak.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GradDolazakID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GradDolazak.Naziv)
        </dd>

        <dt>
            Vozac
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PutniNalog.Vozac.PunoIme)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kilometraza)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kilometraza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrijevozIznos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrijevozIznos)
        </dd>

    </dl>

        <input type="button" class="btn btn-primary" value="Export to XML" id="btnExport" />
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDRelacija  }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#btnExport').on('click', function () {

                var idRel = $('#idRel').text().replace(/\s/g, "");
                $.ajax({
                    url: '/Moj/ExportXML',
                    data: { idRel: idRel },
                    success: function () {
                        window.location = '/Moj/ExportXML?idRel=' + idRel;
                    },
                    fail: function () {
                        alert('Error has occured.');
                    }
                })
                console.log(idRel);
            }

            )
        })
    </script>    
}

MVC/Zadatak/Views/Relacija/Edit.cshtml
@model Zadatak.Models.RelacijaViewModel

@{
    ViewBag.Title = "Uređivanje relacija";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Relacije</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IDRelacija)
    <div class="form-group">
        @Html.LabelFor(model => model.GradPolazakID, "GradPolazak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GradPolazakID", new SelectList(Model.ListaGradova, "IDGrad", "Naziv"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.GradDolazakID, "GradDolazak", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GradDolazakID", new SelectList(Model.ListaGradova, "IDGrad", "Naziv"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PutniNalogID, "Putni nalog", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("PutniNalogID", new SelectList(Model.ListaPutnihNaloga, "IDPutniNalog", "PrikazNaloga"), htmlAttributes: new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kilometraza, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Kilometraza, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kilometraza, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrijevozIznos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PrijevozIznos, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PrijevozIznos, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/Zadatak/Views/Relacija/Index.cshtml
@model IEnumerable<Zadatak.Models.RelacijaViewModel>

@{
    ViewBag.Title = "Pregled relacija";
}

<h2>Relacije</h2>
@Html.ActionLink("Dodaj novu", "Create")
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GradPolazakID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GradDolazakID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PutniNalogID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kilometraza)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PrijevozIznos)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GradPolazak.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GradDolazak.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PutniNalog.PrikazNaloga)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kilometraza)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrijevozIznos)
            </td>
            <td>
                @Html.ActionLink("Detalji", "Details", "Relacija", new { id = item.IDRelacija }, null) |
                @Html.ActionLink("Obriši", "Delete", "Relacija", new { id = item.IDRelacija }, null)
            </td>
        </tr>
    }

</table>
@using (Html.BeginForm("ImportXML", "Moj", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.Hidden("type", 0)
    <input type="file" name="file" value="Odaberi" />
    <input type="submit" value="Dodaj" class="btn btn-primary">

}
@*<input type="button" value="Import from XML" class="btn btn-primary" id="btnImport" style="display:block;" />
    <input type="file" id="fileInput" style="display:none;" />*@
@Html.Partial("~/Views/Shared/_Navigation.cshtml")


@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#btnImport').on('click', function () {
                $('#fileInput').click();
            }

            );
            $('#fileInput').change(function (e) {
                var rawFile = new XMLHttpRequest();
                rawFile.open("GET", "file:///D:/Faks/PPPK_MVC/Zadatak/Relations/REL-2.xml", false);
                rawFile.onreadystatechange = function () {
                    if (rawFile.readyState === 4) {
                        if (rawFile.status === 200 || rawFile.status == 0) {
                            var allText = rawFile.responseText;
                            alert(allText);
                        }
                    }
                }
                rawFile.send(null);


            });
        });
    </script>
}